language: node_js
node_js:
  - "0.12"
  - "iojs-2"
  - "iojs-3"
  - "4.0"
script: npm run $NPM_COMMAND
sudo: false
env:
  matrix:
    - NPM_COMMAND=test
    - NPM_COMMAND=test-with-coverage
matrix:
  exclude:
    # don't collect code coverage more than once
    - node_js: "iojs-2"
      env: NPM_COMMAND=test-with-coverage
    - node_js: "iojs-3"
      env: NPM_COMMAND=test-with-coverage
    - node_js: "4.0"
      env: NPM_COMMAND=test-with-coverage
    # don't test 0.12 more than once
    - node_js: "0.12"
      env: NPM_COMMAND=test
